import Head from 'next/head';

const HTMLHead: any = () => {
  return (
    <Head>
      <title>franklx2</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HTMLHead;
